#!/usr/bin/env python

"""Find and print the sequences with identical IDs."""

import sys

from Bio import SeqIO

seen = set()
for rec in SeqIO.parse(sys.argv[1], 'fasta'):
    acc = rec.id
    if acc in seen:
        print rec.format('fasta')
    else:
        seen.add(acc)

